In [22]:
import pandas as pd

data = pd.read_csv("../../data/raw/kathmandu_full_raw_2023_2024.csv")

Datetime format conversion and sorting (although already sorted)

In [25]:

data["time"] = pd.to_datetime(data["time"])
data = data.sort_values("time").reset_index(drop=True)
data.head(3)

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,surface_pressure
0,2023-01-01 00:00:00,83.4,119.2,1689,38.0,12.9,67,7.9,88,1.1,162,872.6
1,2023-01-01 01:00:00,82.2,117.6,1594,31.5,13.2,70,8.0,85,2.9,150,872.3
2,2023-01-01 02:00:00,80.8,115.7,1504,24.6,13.6,73,8.0,81,4.1,135,871.9

Create target column. For instance i, target is PM2.5 of instance (i+1) i.e. PM2.5 after 1 hour.

In [32]:
data["target"] = data["pm2_5"].shift(-1)
data.head(3)

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,surface_pressure,target
0,2023-01-01 00:00:00,83.4,119.2,1689,38.0,12.9,67,7.9,88,1.1,162,872.6,82.2
1,2023-01-01 01:00:00,82.2,117.6,1594,31.5,13.2,70,8.0,85,2.9,150,872.3,80.8
2,2023-01-01 02:00:00,80.8,115.7,1504,24.6,13.6,73,8.0,81,4.1,135,871.9,78.2